name: Deploy Backend to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Clean npm Cache
      run: npm cache clean --force

    - name: Install Dependencies
      working-directory: PP2/BackEnd
      run: npm install --legacy-peer-deps

    - name: Generate Prisma Client
      working-directory: PP2/BackEnd
      run: npx prisma generate

    - name: Build Backend
      working-directory: PP2/BackEnd
      run: npm run build

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: SFJScriptorium
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

